### ISSUE TITLE
RGB & BGR

### ISSUE THREAD

**Issue by dihuangdh** [ddshan/hand_object_detector#1]
Hi @ddshan 

Thanks for your awesome work.

The demo.py support both image input and webcam input. However, you use `imread` to read images, which return `RGB`; and use `cv2` to read video, which should return `BGR`. Is this wrong?

https://github.com/ddshan/hand_object_detector/blob/6b46cb01a977323fe5eeed68f676b0888c87a4c0/demo.py#L254-L270

**Comment by ddshan** [comment]
Thank you for pointing out! Sorry about the inconsistent imread() methods. I have fixed the code.
