### ISSUE TITLE
How do I define CUDA_PATH?

### ISSUE THREAD

**Issue by yamand16** [ddshan/hand_object_detector#16]
Hello,

Thank you for your great project! I am trying to build to use GPU. However, I got an error since I am using Conda virtual environment. The CUDA_PATH is None and when I define the CUDA_PATH by using the path under conda environment. However, since NVCC is not there, I get the following error.

`/home/user_name/miniconda3/pkgs/cudatoolkit-11.0.221-h6bb024c_0/bin/nvcc: not found`

CUDA is not available in the system. Under this circumstances, is it possible to solve this problem?

Thank you and best regards.

**Comment by yamand16** [comment]
This helped me to solve the problem!

https://stackoverflow.com/questions/56470424/nvcc-missing-when-installing-cudatoolkit

**Comment by ddshan** [comment]
@yamand16 Great. Let me know if you have any other questions.
