### ISSUE TITLE
How can I make annotations for my own dataset?

### ISSUE THREAD

**Issue by lllxq** [ddshan/hand_object_detector#18]
Hi @ddshan , thank you for your excellent code. I want to know how to make annotations for my own dataset so I can possibly fine-tune on it?
I already know how to make bbox annotations for hands and objects, but I don't know how to annotate hand_side, contact_state and offset, could you please tell me how to make these annotations? Thank you!
![image](https://user-images.githubusercontent.com/55610986/145392207-3ecbf2b8-3d9b-499e-bf3c-2d1ce85ae8db.png)

**Comment by ddshan** [comment]
Hi,
I recommend you to check the [supplimental](https://fouheylab.eecs.umich.edu/~dandans/projects/100DOH/file/supp.pdf) for our paper. In **A.2 Data Annotation**, we introduced how we use an online labeling platform to make those annotations.

**Comment by faderani** [comment]
Hi @lllxq @ddshan,

Does any of you know a free tool that I can use to annotate my data with the same format? I think I need to customize an open-source annotation tool that are there but if you know a tool that supports adding custom fields let me know.
