### ISSUE TITLE
How can i get ego datasets?

### ISSUE THREAD

**Issue by sh2120170809** [ddshan/hand_object_detector#19]
i would like to use 100DOH+ego dataset to train my own hand detection model, how can i get ego dataset?

**Comment by ddshan** [comment]
Hi, please just send me an email for the annotated ego data.

**Comment by twotwo2** [comment]
@ddshan Thanks for your excellent work. I want to use ego dataset to train a model, can you send the annotated ego data to my email (2111912036@zjut.edu.cn). I would be grateful if I could get a reply from you.

**Comment by LZ-CH** [comment]
@ddshan Thanks for your excellent work. I also want to use ego dataset to train a model, can you send the annotated ego data to my email ([luojzh5@mail2.sysu.edu.cn](mailto:luojzh5@mail2.sysu.edu.cn))? I would be grateful if I could get a reply from you.

**Comment by 1998CHC** [comment]
@ddshan Thanks for your excellent work! Could you please kindly share the download links for the Ego dataset and its annotations to my email (changhch5@mail2.sysu.edu.cn)? I would be very grateful!
