### ISSUE TITLE
Size mismatch error with pre-trained model

### ISSUE THREAD

**Issue by Tonyzhang2000** [ddshan/hand_object_detector#25]
Hi, I got error message: "size mismatch for extension_layer.hand_contact_state_layer.3.weight: copying a param with shape torch.Size([5, 32]) from checkpoint, the shape in current model is torch.Size([4, 32])." when running your code with provided pre-trained model. A temporary work around would be checkout to previous version.

**Comment by ddshan** [comment]
Hi, thanks for pointing it out. I accidentally pushed a commit containing some of my trials of another experiment. I have reverted it back and everything should work now.
